event/urls.py
from django.urls import path

from event.views import EventCreateView, EventListView

app_name = 'event'
urlpatterns = [
    path('', EventListView.as_view(), name='list'),
    path('create/', EventCreateView.as_view(), name='create'),
]

sportsinsu/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('event/', include('event.urls', namespace='event'))
]

event/models.py
import uuid

from django.db import models


class Event(models.Model):
    class Meta:
        verbose_name = '행사'
        verbose_name_plural = verbose_name
        ordering = ('-register_at',)

    id = models.UUIDField(default=uuid.uuid4, null=False, blank=False, unique=True, primary_key=True, editable=False)
    name = models.CharField(max_length=300, null=False, blank=False, unique=True, verbose_name='행사명')
    register_at = models.DateTimeField(auto_now_add=True, verbose_name='생성일')
    main_image = models.ImageField(null=False, blank=False, verbose_name='행사 대표 이미지')
    event_start = models.DateTimeField(null=False, blank=False, verbose_name='행사 시작일시')
    event_end = models.DateTimeField(null=False, blank=False, verbose_name='행사 종료일시')
    insu_rgst_start = models.DateTimeField(null=False, blank=False, verbose_name='보험가입 시작일시')
    insu_rgst_end = models.DateTimeField(null=False, blank=False, verbose_name='보험가입 종료일시')
    description = models.TextField(null=False, blank=False, verbose_name='행사설명')
    attendants = models.ManyToManyField('event.Attendant', through='event.EventAttendantThrough')


class EventAttendantThrough(models.Model):
    event = models.ForeignKey(Event, null=False, blank=False, on_delete=models.PROTECT, verbose_name='이벤트')
    attendant = models.ForeignKey('event.Attendant', null=False, blank=False, on_delete=models.PROTECT,
                                  verbose_name='참가자')


class Attendant(models.Model):
    class Meta:
        verbose_name = '참가자'
        verbose_name_plural = verbose_name

    id = models.UUIDField(default=uuid.uuid4, null=False, blank=False, unique=True, primary_key=True, editable=False)
    name = models.CharField(max_length=30, null=False, blank=False, verbose_name='성명')
    cellphone = models.CharField(max_length=11, null=False, blank=False, verbose_name='휴대전화')
    birthdate = models.DateField(null=True, blank=True, verbose_name='생년월일')

event/forms.py
from crispy_forms.helper import FormHelper
from django import forms

from event.models import Event


class EventCreateForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ['name', 'main_image', 'event_start', 'event_end', 'insu_rgst_start', 'insu_rgst_end',
                  'description']

    def __init__(self, *args, **kwargs):
        super(EventCreateForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.form_method = 'POST'

event/views.py
import django_filters
from django.shortcuts import render
from django.views import View
from django.views.generic import ListView
import django_tables2 as tables
from django_filters.views import FilterView
from django_tables2 import SingleTableView, SingleTableMixin

from event.forms import EventCreateForm
from event.models import Event


class EventFilter(django_filters.FilterSet):
    class Meta:
        model = Event
        fields = ['name', 'event_start', 'insu_rgst_start']


class EventTable(tables.Table):
    class Meta:
        model = Event
        template_name = "django_tables2/bootstrap4.html"
        fields = ("name", "event_start", "insu_rgst_start")


class EventListView(SingleTableMixin, FilterView):
    template_name = 'event/list.html'
    model = Event
    table_class = EventTable
    filterset_class = EventFilter


class EventCreateView(View):
    def get(self, request):
        # 이벤트 생성 폼
        form = EventCreateForm()
        template_name = 'event/create.html'
        context = {'form': form}
        return render(request, template_name=template_name, context=context)

    def post(self, request):
        # 이벤트 생성
        pass

templates/base.html
{% load static %}
{% load bootstrap4 %}

<!doctype html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <title>체육행사보험</title>
    <style>
        body {
            padding-top: 80px;
        }
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>
</head>
<body>
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <a class="navbar-brand" href="#">체육행사보험</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
            aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'event:list' %}">행사<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
            </li>
        </ul>
    </div>
</nav>

<main role="main" class="container">
    {% block content %}
    {% endblock %}
</main><!-- /.container -->
</body>
</html>

templates/event/create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
{% crispy form %}
{% endblock %}

templates/event/list.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load render_table from django_tables2 %}

{% block content %}
    <div class="row">
        <div class="col-12 mb-3">
            <div class="row">
                <div class="col-md-10">
                    <form action="" method="get" class="form form-inline">
                        {% bootstrap_form filter.form layout='inline' %}
                        {% bootstrap_button '검색' %}
                    </form>
                </div>
                <div class="col-md-2">
                    <a class="btn btn-primary btn-block" href="{% url 'event:create' %}">행사생성</a>
                </div>
            </div>
        </div>
        <div class="col-12">
            {% render_table table %}
        </div>
    </div>
{% endblock %}